// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211122151527_ImagesAndDescriptionWithoutSlug")]
    partial class ImagesAndDescriptionWithoutSlug
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            MoviesId = 1
                        },
                        new
                        {
                            ActorsId = 3,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 4,
                            MoviesId = 2
                        },
                        new
                        {
                            ActorsId = 5,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 6,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 10,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 11,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 31,
                            MoviesId = 3
                        },
                        new
                        {
                            ActorsId = 7,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 8,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 9,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 10,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 11,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 12,
                            MoviesId = 4
                        },
                        new
                        {
                            ActorsId = 13,
                            MoviesId = 5
                        },
                        new
                        {
                            ActorsId = 14,
                            MoviesId = 5
                        },
                        new
                        {
                            ActorsId = 15,
                            MoviesId = 5
                        },
                        new
                        {
                            ActorsId = 16,
                            MoviesId = 6
                        },
                        new
                        {
                            ActorsId = 17,
                            MoviesId = 6
                        },
                        new
                        {
                            ActorsId = 18,
                            MoviesId = 6
                        },
                        new
                        {
                            ActorsId = 7,
                            MoviesId = 7
                        },
                        new
                        {
                            ActorsId = 19,
                            MoviesId = 7
                        },
                        new
                        {
                            ActorsId = 20,
                            MoviesId = 7
                        },
                        new
                        {
                            ActorsId = 21,
                            MoviesId = 7
                        },
                        new
                        {
                            ActorsId = 21,
                            MoviesId = 8
                        },
                        new
                        {
                            ActorsId = 22,
                            MoviesId = 8
                        },
                        new
                        {
                            ActorsId = 23,
                            MoviesId = 8
                        },
                        new
                        {
                            ActorsId = 24,
                            MoviesId = 8
                        },
                        new
                        {
                            ActorsId = 12,
                            MoviesId = 9
                        },
                        new
                        {
                            ActorsId = 25,
                            MoviesId = 9
                        },
                        new
                        {
                            ActorsId = 26,
                            MoviesId = 9
                        },
                        new
                        {
                            ActorsId = 27,
                            MoviesId = 10
                        },
                        new
                        {
                            ActorsId = 28,
                            MoviesId = 10
                        },
                        new
                        {
                            ActorsId = 29,
                            MoviesId = 10
                        },
                        new
                        {
                            ActorsId = 30,
                            MoviesId = 11
                        },
                        new
                        {
                            ActorsId = 32,
                            MoviesId = 11
                        },
                        new
                        {
                            ActorsId = 31,
                            MoviesId = 11
                        },
                        new
                        {
                            ActorsId = 5,
                            MoviesId = 12
                        },
                        new
                        {
                            ActorsId = 33,
                            MoviesId = 12
                        },
                        new
                        {
                            ActorsId = 34,
                            MoviesId = 12
                        },
                        new
                        {
                            ActorsId = 10,
                            MoviesId = 12
                        },
                        new
                        {
                            ActorsId = 35,
                            MoviesId = 13
                        },
                        new
                        {
                            ActorsId = 7,
                            MoviesId = 13
                        },
                        new
                        {
                            ActorsId = 36,
                            MoviesId = 14
                        },
                        new
                        {
                            ActorsId = 37,
                            MoviesId = 14
                        },
                        new
                        {
                            ActorsId = 38,
                            MoviesId = 15
                        },
                        new
                        {
                            ActorsId = 39,
                            MoviesId = 15
                        },
                        new
                        {
                            ActorsId = 40,
                            MoviesId = 15
                        },
                        new
                        {
                            ActorsId = 21,
                            MoviesId = 15
                        },
                        new
                        {
                            ActorsId = 23,
                            MoviesId = 15
                        },
                        new
                        {
                            ActorsId = 41,
                            MoviesId = 16
                        },
                        new
                        {
                            ActorsId = 42,
                            MoviesId = 16
                        },
                        new
                        {
                            ActorsId = 43,
                            MoviesId = 16
                        },
                        new
                        {
                            ActorsId = 44,
                            MoviesId = 16
                        });
                });

            modelBuilder.Entity("Domain.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1937, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(926),
                            Description = "Jack Nicholson, an American actor, producer, director and screenwriter, is a three-time Academy Award winner and twelve-time nominee. Nicholson is also notable for being one of two actors - the other being Michael Caine - who have received an Oscar nomination in every decade from the '60s through the '00s. Nicholson was born on April 22, 1937, in ... ",
                            Image = "Jack Nicholson--928401a8-56b7-4b88-beb6-90e19399789c.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(937),
                            Name = "Jack Nicholson",
                            Rating = 11.0,
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1949, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1820),
                            Description = "Shelley Alexis Duvall was born in Fort Worth, Texas, the first child to Bobbie Ruth (Massengale, 1929-2020), a real estate broker, and Robert Richardson Duvall (1919-1994), a lawyer. At the time of her birth, her mother was visiting her grandmother in Fort Worth, though Duvall was raised in Houston. During her childhood, Shelley's mother ... ",
                            Image = "Shelley Duvall--0cd507e8-1bb4-4230-9422-bff54b5307a2.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1821),
                            Name = "Shelley Duvall",
                            Rating = 8.0,
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1936, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1823),
                            Description = "all, slim, remote and boyishly handsome, one of Keir Dullea's most arresting features is his pale blue eyes, which featured in a number of watershed films of the 1960s. His major breakthrough (providing him legendary status) was the starring role as astronaut Dave Bowman in Stanley Kubrick's 2001: A Space Odyssey. After that, he persevered quite ...",
                            Image = "Keir Dullea--c1354574-199c-4ec3-836a-ed880b3f2156.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1823),
                            Name = "Keir Dullea",
                            Rating = 9.0,
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1937, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1825),
                            Description = "Gary Lockwood was born John Gary Yurosek in Van Nuys, California to John and Margaret Emma (Kiel) Yurosek . He attended UCLA on a football scholarship. He began his career as a movie stuntman, and a stand-in for Anthony Perkins, prior to his acting debut in 1959 in an uncredited bit role in Warlock (1959). He also appeared as a police officer in ...",
                            Image = "Gary Lockwood--3c477cc2-7e75-4c84-925d-cfda401b50cc.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1825),
                            Name = "Gary Lockwood",
                            Rating = 8.5999999999999996,
                            Year = 0
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1974, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1826),
                            Description = "Christian Charles Philip Bale was born in Pembrokeshire, Wales, UK on January 30, 1974, to English parents Jennifer Jenny (James) and David Bale. His mother was a circus performer and his father, who was born in South Africa, was a commercial pilot. The family lived in different countries throughout Bale's childhood, including England, Portugal,... ",
                            Image = "Christian Bale--78888617-872a-4041-8ca2-57bd6f6b11b2.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1827),
                            Name = "Christian Bale",
                            Rating = 11.5,
                            Year = 0
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1979, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1828),
                            Description = "When hunky, twenty-year-old heart-throb Heath Ledger first came to the attention of the public in 1999, it was all too easy to tag him as a pretty boy and an actor of little depth. He spent several years trying desperately to sway this image, but this was a double-edged sword. His work comprised nineteen films, including 10 Things I Hate About ...",
                            Image = "Heath Ledger--5bf42bcc-786a-4b70-a185-d4eade846817.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1828),
                            Name = "Heath Ledger",
                            Rating = 10.300000000000001,
                            Year = 0
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1829),
                            Description = "Few actors in the world have had a career quite as diverse as Leonardo DiCaprio's. DiCaprio has gone from relatively humble beginnings, as a supporting cast member of the sitcom Growing Pains (1985) and low budget horror movies, such as Critters 3 (1991), to a major teenage heartthrob in the 1990s, as the hunky lead actor in movies such as Romeo +...",
                            Image = "Leonardo DiCaprio--5ad2fa35-054b-4fce-8e84-916b9aa773f0.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1830),
                            Name = "Leonardo DiCaprio",
                            Rating = 12.1,
                            Year = 0
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1981, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1831),
                            Description = "Joseph Leonard Gordon-Levitt was born February 17, 1981 in Los Angeles, California, to Jane Gordon and Dennis Levitt. Joseph was raised in a Jewish family with his late older brother, Dan Gordon-Levitt, who passed away in October 2010. His parents worked for the Pacifica Radio station KPFK-FM and his maternal grandfather, Michael Gordon, had been ...",
                            Image = "Joseph Gordon-Levitt--e3d1fd7c-ce25-4bb7-add8-d12950640509.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1831),
                            Name = "Joseph Gordon-Levitt",
                            Rating = 9.5999999999999996,
                            Year = 0
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1977, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1832),
                            Description = "With his breakthrough performance as Eames in Christopher Nolan's sci-fi thriller Inception (2010), English actor Tom Hardy has been brought to the attention of mainstream audiences worldwide. However, the versatile actor has been steadily working on both stage and screen since his television debut in the miniseries Band of Brothers (2001). After ...",
                            Image = "Tom Hardy--cc26260e-c69f-4262-925b-32f0af2b8fc5.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1833),
                            Name = "Tom Hardy",
                            Rating = 10.199999999999999,
                            Year = 0
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1933, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1835),
                            Description = "Michael Caine was born Maurice Joseph Micklewhite in London, to Ellen Frances Marie (Burchell), a charlady, and Maurice Joseph Micklewhite, a fish-market porter. He left school at age 15 and took a series of working-class jobs before joining the British army and serving in Korea during the Korean War, where he saw combat. Upon his return to ...",
                            Image = "Michael Cain--4a1329ba-f3c3-469f-89d5-ee1c5c3eadcd.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1835),
                            Name = "Michael Caine",
                            Rating = 9.1999999999999993,
                            Year = 0
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateTime(1976, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1837),
                            Description = "Striking Irish actor Cillian Murphy was born in Douglas, the oldest child of Brendan Murphy, who works for the Irish Department of Education, and a mother who is a teacher of French. He has three younger siblings. Murphy was educated at Presentation Brothers College, Cork. He went on to study law at University College Cork, but dropped out after ...",
                            Image = "Cillian Murphy--2265ad64-8a71-4da4-a898-53c1a9c15791.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1838),
                            Name = "Cillian Murphy",
                            Rating = 10.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateTime(1975, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1839),
                            Description = "Academy Award-winning actress Marion Cotillard was born on September 30, 1975 in Paris. Cotillard is the daughter of Jean-Claude Cotillard, an actor, playwright and director, and Niseema Theillaud, an actress and drama teacher. Her father's family is from Brittany. Raised in Orléans, France, she made her acting debut as a child with a role in one ... ",
                            Image = "Marion Cotillard--ab70db7f-1474-4683-bfcc-a1051b85691c.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1840),
                            Name = "Marion Cotillard",
                            Rating = 10.300000000000001,
                            Year = 0
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateTime(1966, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1840),
                            Description = "Jason Flemyng was born on September 25, 1966 in Putney, London, England as Jason Iain Flemyng. He is an actor and producer, known for Lock, Stock and Two Smoking Barrels (1998), The Curious Case of Benjamin Button (2008) and Deep Rising (1998). He has been married to Elly Fairman since June 6, 2008.",
                            Image = "Jason Flemyng--39ae09e1-8325-43b0-a869-d662a56b5818.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1841),
                            Name = "Jason Flemyng",
                            Rating = 9.3000000000000007,
                            Year = 0
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateTime(1967, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1842),
                            Description = "Jason Statham was born in Shirebrook, Derbyshire, to Eileen (Yates), a dancer, and Barry Statham, a street merchant and lounge singer. He was a Diver on the British National Diving Team and finished twelfth in the World Championships in 1992. He has also been a fashion model, black market salesman and finally of course, actor. He received the ...",
                            Image = "Jason Statham--571b29e4-0eca-4f79-a832-6ab4a0ed906d.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1842),
                            Name = "Jason Statham",
                            Rating = 10.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateTime(1965, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1843),
                            Description = "Vincent Peter Jones was born on January 5, 1965 in Watford, England. He first came to public notice as a professional footballer, playing in the English Football League. Noted as one of football's hard men, he leaped to fame when a photographer, at a match, snapped him marking Newcastle United's Paul Gascoigne, by grabbing his testicles. He has ...",
                            Image = "Vinnie Jones--dc0031b4-5b0d-4b71-ba77-e39b2e1601d0.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1844),
                            Name = "Vinnie Jones",
                            Rating = 9.6999999999999993,
                            Year = 0
                        },
                        new
                        {
                            Id = 16,
                            Birthday = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1845),
                            Description = "Robert Downey Jr. has evolved into one of the most respected actors in Hollywood. With an amazing list of credits to his name, he has managed to stay new and fresh even after over four decades in the business. Downey was born April 4, 1965 in Manhattan, New York, the son of writer, director and filmographer Robert Downey Sr. and actress Elsie Downey...",
                            Image = "Robert Downey Jr--8d269864-287f-40ba-b86d-74f00329be91.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1845),
                            Name = "Robert Downey Jr.",
                            Rating = 11.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 17,
                            Birthday = new DateTime(1972, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1846),
                            Description = "Jude Law is an English actor. Law has been nominated for two Academy Awards and continues to build a prolific body of work that spans from early successes such as Gattaca (1997) and The Talented Mr. Ripley (1999) to more recent turns as Dr. John Watson in Sherlock Holmes (2009) and Sherlock Holmes: A Game of Shadows (2011), as Hugo's father in Hugo...",
                            Image = "Jude Law--2fe2b13d-b8e6-489e-997e-f62c8c1e0725.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1847),
                            Name = "Jude Law",
                            Rating = 9.6999999999999993,
                            Year = 0
                        },
                        new
                        {
                            Id = 18,
                            Birthday = new DateTime(1963, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1848),
                            Description = "British actor Mark Strong, who played Jim Prideaux in the 2011 remake of Tinker Tailor Soldier Spy (2011), is often cast as cold, calculating villains. But before he became a famous actor, he intended to pursue a career in law. Strong was born Marco Giuseppe Salussolia in London, England, to an Austrian mother and an Italian father. His father left...",
                            Image = "Mark Strong--bde9e7fb-7e3f-418d-97d2-826e041171d6.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1848),
                            Name = "Mark Strong",
                            Rating = 9.5999999999999996,
                            Year = 0
                        },
                        new
                        {
                            Id = 19,
                            Birthday = new DateTime(1967, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1849),
                            Description = "Jamie Foxx is an American actor, singer and comedian. He won an Academy Award for Best Actor, BAFTA Award for Best Actor in a Leading Role, and Golden Globe Award for Best Actor in a Musical or Comedy, for his work in the biographical film Ray (2004). The same year, he was nominated for the Academy Award for Best Supporting Actor for his role in ...",
                            Image = "Jamie Foxx--44f9c50f-bbbe-4049-8f8c-e86df663cfb4.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1850),
                            Name = "Jamie Foxx",
                            Rating = 10.1,
                            Year = 0
                        },
                        new
                        {
                            Id = 20,
                            Birthday = new DateTime(1956, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1851),
                            Description = "Christoph Waltz is an Austrian-German actor. He is known for his work with American filmmaker Quentin Tarantino, receiving acclaim for portraying SS-Standartenführer Hans Landa in Inglourious Basterds (2009) and bounty hunter Dr. King Schultz in Django Unchained (2012). For each performance, he won an Academy Award, a BAFTA Award, and a Golden ...",
                            Image = "Christoph Waltz--b7bd4de2-1536-405f-b460-ec32a601cb70.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1851),
                            Name = "Christoph Waltz",
                            Rating = 10.5,
                            Year = 0
                        },
                        new
                        {
                            Id = 21,
                            Birthday = new DateTime(1948, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1852),
                            Description = "Samuel L. Jackson is an American producer and highly prolific actor, having appeared in over 100 films, including Die Hard: With a Vengeance (1995), Unbreakable (2000), Shaft (2000), The 51st State (2001), Black Snake Moan (2006), Snakes on a Plane (2006), and the Star Wars prequel trilogy (1999-2005), as well as the Marvel Cinematic Universe. ...",
                            Image = "Samuel L Jackson--cbb52077-7f31-4e7d-b0fe-73a35589a1ed.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1853),
                            Name = "Samuel L. Jackson",
                            Rating = 11.699999999999999,
                            Year = 0
                        },
                        new
                        {
                            Id = 22,
                            Birthday = new DateTime(1951, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1854),
                            Description = "Kurt Vogel Russell was born on March 17, 1951 in Springfield, Massachusetts, to Louise Julia Russell (née Crone), a dancer, and Bing Russell, an actor. He is of English, German, Scottish and Irish descent. His first roles were as a child on television series, including a lead role on the Western series The Travels of Jaimie McPheeters (1963). ...",
                            Image = "Kurt Russell--f9f3a0e2-b112-49cb-ab8c-d0dbb0353409.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1854),
                            Name = "Kurt Russell",
                            Rating = 10.300000000000001,
                            Year = 0
                        },
                        new
                        {
                            Id = 23,
                            Birthday = new DateTime(1961, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1855),
                            Description = "Often mistaken for an American because of his skill at imitating accents, actor Tim Roth was born Timothy Simon Roth on May 14, 1961 in Lambeth, London, England. His mother, Ann, was a teacher and landscape painter. His father, Ernie, was a journalist who had changed the family name from Smith to Roth; Ernie was born in Brooklyn, New York, to ... ",
                            Image = "Tim Roth--12106310-2f00-410a-8cbb-20b4c142d976.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1856),
                            Name = "Tim Roth",
                            Rating = 10.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 24,
                            Birthday = new DateTime(1957, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1857),
                            Description = "Michael Madsen's long career spans nearly 40 years and more than 170 films in which he has played memorable characters in myriad box office hits, including: Kill Bill: Vol. 1 (2003), Kill Bill: Vol. 2 (2004) Sin City (2005), Hell Ride (2008), Die Another Day (2002), Donnie Brasco (1997), Species (1995), The Getaway (1994), Thelma & Louise (...",
                            Image = "Michael Madsen--49923597-e932-4797-8f2c-141e4855f3af.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1857),
                            Name = "Michael Madsen",
                            Rating = 10.1,
                            Year = 0
                        },
                        new
                        {
                            Id = 25,
                            Birthday = new DateTime(1961, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1858),
                            Description = "Samy Naceri is born in Paris from an Algerian father and a French mother. He grew up in the suburbs of Paris in a modest family of seven siblings. Since his youngest age, Samy dreamt about making movies. After many years of struggling and hard work, he will finally have a chance to meet a famous casting director (Bruno Delahaye) who will offer him ...",
                            Image = "Samy Naceri--6bfda92a-99f8-47ec-a67f-ce41682fcae5.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1858),
                            Name = "Samy Naceri",
                            Rating = 10.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 26,
                            Birthday = new DateTime(1968, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1859),
                            Description = "Frédéric Diefenthal was born on July 26, 1968 in Saint-Mandé, Val-de-Marne, France as Frédéric Pierre Diefenthal-Girau-Guyard. He is an actor and producer, known for Taxi (1998), Taxi 4 (2007) and Taxi 3 (2003). He was previously married to Gwendoline Hamon.",
                            Image = "Frédéric Diefenthal--c5cb3a61-5bd5-4a21-9dba-a3708c1a5ba9.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1860),
                            Name = "Frédéric Diefenthal",
                            Rating = 9.6999999999999993,
                            Year = 0
                        },
                        new
                        {
                            Id = 27,
                            Birthday = new DateTime(1943, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1862),
                            Description = "One of the greatest actors of all time, Robert De Niro was born on August 17, 1943 in Manhattan, New York City, to artists Virginia (Admiral) and Robert De Niro Sr. His paternal grandfather was of Italian descent, and his other ancestry is Irish, English, Dutch, German, and French. He was trained at the Stella Adler Conservatory and the American ...",
                            Image = "Robert De Niro--4b3892c6-4bb5-4fdd-a0d9-d14a0d09f6f3.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1862),
                            Name = "Robert De Niro",
                            Rating = 12.1,
                            Year = 0
                        },
                        new
                        {
                            Id = 28,
                            Birthday = new DateTime(1958, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1863),
                            Description = "Michelle Pfeiffer was born in Santa Ana, California to Dick and Donna Pfeiffer. She has an older brother and two younger sisters - Dedee Pfeiffer, and Lori Pfeiffer, who both dabbled in acting and modeling but decided against making it their lives' work. She graduated from Fountain Valley High School in 1976, and attended one year at the Golden ...",
                            Image = "Michelle Pfeiffer--c0b03f74-aa00-4780-904e-63f987105c7e.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1864),
                            Name = "Michelle Pfeiffer",
                            Rating = 10.1,
                            Year = 0
                        },
                        new
                        {
                            Id = 29,
                            Birthday = new DateTime(1946, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1865),
                            Description = "Tommy Lee Jones was born in San Saba, Texas, the son of Lucille Marie (Scott), a police officer and beauty shop owner, and Clyde C. Jones, who worked on oil fields. Tommy himself worked in underwater construction and on an oil rig. He attended St. Mark's School of Texas, a prestigious prep school for boys in Dallas, on a scholarship, and went to ...",
                            Image = "Tommy Lee Jones--3dae989f-7820-4935-b9df-e838db27bdf6.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1865),
                            Name = "Tommy Lee Jones",
                            Rating = 11.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 30,
                            Birthday = new DateTime(1948, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1866),
                            Description = "Jean Reno was born Juan Moreno y Herrera-Jiménez in Casablanca, Morocco, to Spanish parents (from Andalucía) who moved to North Africa to seek work. His father was a linotypist. Reno settled in France at 17. He began studying drama and has credits in French television and theater as well as films. His first two marriages both ended in divorce, and... ",
                            Image = "Jean Reno--5fb8a62d-76ef-4dc2-9395-9c58cad00ca9.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1867),
                            Name = "Jean Reno",
                            Rating = 11.699999999999999,
                            Year = 0
                        },
                        new
                        {
                            Id = 31,
                            Birthday = new DateTime(1958, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1868),
                            Description = "Gary Oldman is a talented English movie star and character actor, renowned for his expressive acting style. One of the most celebrated thespians of his generation, with a diverse career encompassing theatre, film and television, he is known for his roles as Sid Vicious in Sid and Nancy (1986), Drexl in True Romance (1993), George Smiley in Tinker ...",
                            Image = "Gary Oldman--b00256e6-4062-48e9-b78c-31987722644e.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1868),
                            Name = "Gary Oldman",
                            Rating = 10.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 32,
                            Birthday = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1869),
                            Description = "Natalie Portman is the first person born in the 1980s to have won the Academy Award for Best Actress (for Black Swan (2010)). Natalie was born Natalie Hershlag on June 9, 1981, in Jerusalem, Israel. She is the only child of Avner Hershlag, a Israeli-born doctor, and Shelley Stevens, an American-born artist (from Cincinnati, Ohio), who also acts as ...",
                            Image = "Natalie Portman--6e1e75b7-0825-4cb9-ad4c-edb1d5e1c066.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1870),
                            Name = "Natalie Portman",
                            Rating = 9.6999999999999993,
                            Year = 0
                        },
                        new
                        {
                            Id = 33,
                            Birthday = new DateTime(1968, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1871),
                            Description = "Hugh Michael Jackman is an Australian actor, singer, multi-instrumentalist, dancer and producer. Jackman has won international recognition for his roles in major films, notably as superhero, period, and romance characters. He is best known for his long-running role as Wolverine in the X-Men film series, as well as for his lead roles in the ...",
                            Image = "Hugh Jackman--cdb0aa4e-8478-4081-bfea-2de2551224b2.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1871),
                            Name = "Hugh Jackman",
                            Rating = 10.6,
                            Year = 0
                        },
                        new
                        {
                            Id = 34,
                            Birthday = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1872),
                            Description = "Scarlett Ingrid Johansson was born on November 22, 1984 in Manhattan, New York City, New York. Her mother, Melanie Sloan is from a Jewish family from the Bronx and her father, Karsten Johansson is a Danish-born architect from Copenhagen. She has a sister, Vanessa Johansson, who is also an actress, a brother, Adrian, a twin brother, Hunter Johansson...",
                            Image = "Scarlett Johansson--e34e9d1f-6866-4384-ba63-93d0bb0ed526.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1873),
                            Name = "Scarlett Johansson",
                            Rating = 10.5,
                            Year = 0
                        },
                        new
                        {
                            Id = 35,
                            Birthday = new DateTime(1967, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1874),
                            Description = "Award-winning actor Mark Ruffalo was born on November 22, 1967, in Kenosha, Wisconsin, of humble means to father Frank Lawrence Ruffalo, a construction painter and Marie Rose (Hebert), a stylist and hairdresser; his father's ancestry is Italian and his mother is of half French-Canadian and half Italian descent. Mark moved with his family to ...",
                            Image = "Mark Ruffalo--f5ce9649-c855-4694-aef3-17d89ea9b46e.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1874),
                            Name = "Mark Ruffalo",
                            Rating = 10.5,
                            Year = 0
                        },
                        new
                        {
                            Id = 36,
                            Birthday = new DateTime(1990, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1875),
                            Description = "Bill Skarsgård was born on August 9, 1990 in Vällingby, Sweden as Bill Istvan Günther Skarsgård. He is an actor and producer, known for It (2017), It: Chapter Two (2019) and Deadpool 2 (2018).",
                            Image = "Bill Skarsgård--346a9d0e-6157-498c-a2c7-cc2b087491c6.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1876),
                            Name = "Bill Skarsgård",
                            Rating = 9.9000000000000004,
                            Year = 0
                        },
                        new
                        {
                            Id = 37,
                            Birthday = new DateTime(2002, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1877),
                            Description = "Sophia Lillis was born in Crown Heights, Brooklyn. She started her acting career at the age of seven, when her stepfather encouraged her to take acting classes at Lee Strasberg Theatre and Film Institute in Manhattan. While studying there, a teacher recommended her for a role in an NYU student film. She then signed a deal with an agent and started...",
                            Image = "Sophia Lillis--ae27a52f-8b18-4f9e-8679-458237baffbb.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1877),
                            Name = "Sophia Lillis",
                            Rating = 9.1999999999999993,
                            Year = 0
                        },
                        new
                        {
                            Id = 38,
                            Birthday = new DateTime(1954, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1878),
                            Description = "John Joseph Travolta was born in Englewood, New Jersey, one of six children of Helen Travolta (née Helen Cecilia Burke) and Salvatore/Samuel J. Travolta. His father was of Italian descent and his mother was of Irish ancestry. His father owned a tire repair shop called Travolta Tires in Hillsdale, NJ. Travolta started acting appearing in a local ...",
                            Image = "John Travolta--042fccc4-fe89-455f-97d8-fc0063203b8b.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1879),
                            Name = "John Travolta",
                            Rating = 10.9,
                            Year = 0
                        },
                        new
                        {
                            Id = 39,
                            Birthday = new DateTime(1970, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1880),
                            Description = "Uma Karuna Thurman was born in Boston, Massachusetts, into a highly unorthodox and internationally-minded family. She is the daughter of Nena Thurman (née Birgitte Caroline von Schlebrügge), a fashion model and socialite who now runs a mountain retreat, and of Robert Thurman (Robert Alexander Farrar Thurman), a professor and academic who is one of...",
                            Image = "Uma Thurman--d7e85d7d-70dd-4c4c-bca6-b535bbc02406.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1880),
                            Name = "Uma Thurman",
                            Rating = 11.0,
                            Year = 0
                        },
                        new
                        {
                            Id = 40,
                            Birthday = new DateTime(1955, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1881),
                            Description = "Actor and musician Bruce Willis is well known for playing wisecracking or hard-edged characters, often in spectacular action films. Collectively, he has appeared in films that have grossed in excess of $2.5 billion USD, placing him in the top ten stars in terms of box office receipts. Walter Bruce Willis was born on March 19, 1955, in ... ",
                            Image = "Bruce Willis--4e95b8ae-dad4-4e7d-bdef-7fc555815c02.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1882),
                            Name = "Bruce Willis",
                            Rating = 11.5,
                            Year = 0
                        },
                        new
                        {
                            Id = 41,
                            Birthday = new DateTime(1964, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1883),
                            Description = "Keanu Charles Reeves, whose first name means cool breeze over the mountains in Hawaiian, was born September 2, 1964 in Beirut, Lebanon. He is the son of Patricia Taylor, a showgirl and costume designer, and Samuel Nowlin Reeves, a geologist. Keanu's father was born in Hawaii, of British, Portuguese, Native Hawaiian, and Chinese ancestry, and ...",
                            Image = "Keanu Reeves--8b83d385-87a2-4b66-bde6-f0130efc3785.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1883),
                            Name = "Keanu Reeves",
                            Rating = 11.699999999999999,
                            Year = 0
                        },
                        new
                        {
                            Id = 42,
                            Birthday = new DateTime(1961, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1884),
                            Description = "Critically hailed for his forceful, militant, authoritative figures and one of Hollywood's most talented and versatile performers, Laurence (John) Fishburne III has been the recipient of numerous awards, including a number of NAACP Image honors. Born in Augusta, Georgia on July 30, 1961, to Hattie Bell (Crawford), a teacher, and Laurence John ...",
                            Image = "Laurence Fishburne--a17f41cd-f562-471d-9c7b-811367255624.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1885),
                            Name = "Laurence Fishburne",
                            Rating = 10.199999999999999,
                            Year = 0
                        },
                        new
                        {
                            Id = 43,
                            Birthday = new DateTime(1967, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1886),
                            Description = "Carrie-Anne Moss was born and raised in Vancouver, Canada. At age 20, after studying at the American Academy of Dramatic Arts, she moved to Europe to pursue a career in modeling. While in Spain she was cast in the TV show Dark Justice which was produced in Barcelona for its first season and Los Angeles for its second. Once in LA, Carrie-Anne was ...",
                            Image = "Carrie-Anne Moss--ced7b68c-ce41-4178-aeb1-bd875150177b.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1886),
                            Name = "Carrie-Anne Moss",
                            Rating = 10.0,
                            Year = 0
                        },
                        new
                        {
                            Id = 44,
                            Birthday = new DateTime(1960, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1887),
                            Description = "Hugo Wallace Weaving was born on April 4, 1960 in Nigeria, to English parents Anne (Lennard), a tour guide and teacher, and Wallace Weaving, a seismologist. Hugo has an older brother, Simon, and a younger sister, Anna, who both also live and work in Australia. During his early childhood, the Weaving family spent most of their time traveling ...",
                            Image = "Hugo Weaving--738b5541-6bee-43ad-bae1-b4ae24db5ddd.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 14, DateTimeKind.Utc).AddTicks(1888),
                            Name = "Hugo Weaving",
                            Rating = 9.6999999999999993,
                            Year = 0
                        });
                });

            modelBuilder.Entity("Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Director");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1928, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 19, DateTimeKind.Utc).AddTicks(9672),
                            Description = "Stanley Kubrick was born in Manhattan, New York City, to Sadie Gertrude (Perveler) and Jacob Leonard Kubrick, a physician. His family were Jewish immigrants (from Austria, Romania, and Russia). Stanley was considered intelligent, despite poor grades at school. Hoping that a change of scenery would produce better academic performance, Kubrick's ...",
                            Image = "Stanley Kubrick--0db9f42e-0a59-4179-a72e-334f5483f5a3.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 19, DateTimeKind.Utc).AddTicks(9679),
                            Name = "Stanley Kubrick",
                            Rating = 12.300000000000001
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(536),
                            Description = "Best known for his cerebral, often nonlinear, storytelling, acclaimed writer-director Christopher Nolan was born on July 30, 1970, in London, England. Over the course of 15 years of filmmaking, Nolan has gone from low-budget independent films to working on some of the biggest blockbusters ever made. At 7 years old, Nolan began making short movies ...",
                            Image = "Christopher Nolan--d28e2806-d48a-4f03-bf09-6be7cf7b7d43.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(537),
                            Name = "Christopher Nolan",
                            Rating = 12.5
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1968, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(539),
                            Description = "Guy Ritchie was born in Hatfield, Hertfordshire, UK on September 10, 1968. After watching Butch Cassidy and the Sundance Kid (1969) as a child, Guy realized that what he wanted to do was make films. He never attended film school, saying that the work of film school graduates was boring and unwatchable. At 15 years old, he dropped out of school and...",
                            Image = "Guy Ritchie--0ec7447e-bfe1-4a5d-a413-cd27ca7447d9.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(539),
                            Name = "Guy Ritchie",
                            Rating = 12.300000000000001
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(540),
                            Description = "Quentin Jerome Tarantino was born in Knoxville, Tennessee. His father, Tony Tarantino, is an Italian-American actor and musician from New York, and his mother, Connie (McHugh), is a nurse from Tennessee. Quentin moved with his mother to Torrance, California, when he was four years old. In January of 1992, first-time writer-director Tarantino's ...",
                            Image = "Quentin Tarantino--f1408446-a750-4d4a-9a34-d3eab361410a.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(541),
                            Name = "Quentin Tarantino",
                            Rating = 13.0
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1959, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(542),
                            Description = "Luc Besson spent the first years of his life following his parents, scuba diving instructors, around the world. His early life was entirely aquatic. He already showed amazing creativity as a youth, writing early drafts of The Big Blue (1988) and The Fifth Element (1997), as an adolescent bored in school. He planned on becoming a marine biologist ...",
                            Image = "Luc Besson-ae52a9f6-7f52-491a-ae0c-10c0f43a00ab.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(543),
                            Name = "Luc Besson",
                            Rating = 12.6
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(1942, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(544),
                            Description = "Martin Charles Scorsese was born on November 17, 1942 in Queens, New York City, to Catherine Scorsese (née Cappa) and Charles Scorsese, who both worked in Manhattan's garment district, and whose families both came from Palermo, Sicily. He was raised in the neighborhood of Little Italy, which later provided the inspiration for several of his films....",
                            Image = "Martin Scorsese--877c1c9a-eb59-4ccd-9638-0a098af349ee.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(544),
                            Name = "Martin Scorsese",
                            Rating = 11.9
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1973, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(545),
                            Description = "Andy Muschietti was born on August 26, 1973 in Buenos Aires, Federal District, Argentina as Andrés Muschietti. He is a producer and director, known for Mama (2013), It (2017) and It: Chapter Two (2019).",
                            Image = "Andy Muschietti--c1b94fad-1a6f-4fec-b86a-cda7c4806877.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(546),
                            Name = "Andy Muschietti",
                            Rating = 10.199999999999999
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1967, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(547),
                            Description = "Director, writer, and producer Lilly Wachowski was born in 1967 in Chicago, the daughter of Lynne, a nurse and painter, and Ron, a businessman. Lilly was educated at Kellogg Elementary School in Chicago, before moving on to Whitney M. Young High School. After graduating from high school, she attended Emerson College in Boston but dropped out. Lilly...",
                            Image = "Lilly Wachowski--c5d08ab1-730d-40f2-a332-d6a226684a50.jpg",
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 20, DateTimeKind.Utc).AddTicks(547),
                            Name = "Lilly Wachowski",
                            Rating = 12.300000000000001
                        });
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(1826),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(1831),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2190),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2191),
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2192),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2193),
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2193),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2194),
                            Name = "Detective"
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2195),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2195),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2196),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 22, DateTimeKind.Utc).AddTicks(2196),
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(6016),
                            Description = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
                            DirectorId = 1,
                            GenreId = 1,
                            Image = "Shining--216171b4-557f-498b-97fb-89265e2f6976.jpg",
                            Length = new TimeSpan(0, 2, 26, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(6022),
                            Name = "Shining",
                            Rating = 10.9,
                            Year = 1980
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7261),
                            Description = "The Monoliths push humanity to reach for the stars; after their discovery in Africa generations ago, the mysterious objects lead mankind on an awesome journey to Jupiter, with the help of H....",
                            DirectorId = 1,
                            GenreId = 3,
                            Image = "2001 A Space Odyssey--4bb2a106-b137-4c41-b87d-ad78bc617c44.jpg",
                            Length = new TimeSpan(0, 2, 29, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7262),
                            Name = "2001: A Space Odyssey",
                            Rating = 10.199999999999999,
                            Year = 1968
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7265),
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            DirectorId = 2,
                            GenreId = 2,
                            Image = "The Dark Knight--843dd091-41c3-48dd-8c87-ffd116d4a2db.jpg",
                            Length = new TimeSpan(0, 2, 32, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7265),
                            Name = "The Dark Knight",
                            Rating = 9.8000000000000007,
                            Year = 2008
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7266),
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the pro...",
                            DirectorId = 2,
                            GenreId = 3,
                            Image = "Inception--c41f5f44-f7d1-4f5a-b9d2-f76006150c35.jpg",
                            Length = new TimeSpan(0, 2, 28, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7267),
                            Name = "Inception",
                            Rating = 11.1,
                            Year = 2010
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7269),
                            Description = "Eddy persuades his three pals to pool money for a vital poker game against a powerful local mobster, Hatchet Harry. Eddy loses, after which Harry gives him a week to pay back 500,000 pounds.",
                            DirectorId = 3,
                            GenreId = 2,
                            Image = "Lock, Stock and Two Smoking Barrels--dd1478a7-0f13-4795-a455-d8ba9b19e4df.jpg",
                            Length = new TimeSpan(0, 1, 47, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7270),
                            Name = "Lock, Stock and Two Smoking Barrels",
                            Rating = 11.0,
                            Year = 1998
                        },
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7271),
                            Description = "Detective Sherlock Holmes and his stalwart partner Watson engage in a battle of wits and brawn with a nemesis whose plot is a threat to all of England.",
                            DirectorId = 3,
                            GenreId = 4,
                            Image = "Sherlock Holmes--7cdcdde5-876c-4694-b9e7-2ce7978d6c04.jpg",
                            Length = new TimeSpan(0, 2, 8, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7271),
                            Name = "Sherlock Holmes",
                            Rating = 9.6999999999999993,
                            Year = 2009
                        },
                        new
                        {
                            Id = 7,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7273),
                            Description = "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.",
                            DirectorId = 4,
                            GenreId = 6,
                            Image = "Django Unchained--ff44c1db-aeca-42d0-9c54-6262b4524d79.jpg",
                            Length = new TimeSpan(0, 2, 45, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7273),
                            Name = "Django Unchained",
                            Rating = 11.0,
                            Year = 2012
                        },
                        new
                        {
                            Id = 8,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7274),
                            Description = "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
                            DirectorId = 4,
                            GenreId = 6,
                            Image = "The Hatefull Eight--430c1969-55b9-46c5-92ef-eb511f72a4e3.jpg",
                            Length = new TimeSpan(0, 2, 48, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7275),
                            Name = "The Hatefull Eight",
                            Rating = 10.0,
                            Year = 2015
                        },
                        new
                        {
                            Id = 9,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7277),
                            Description = "To work off his tarnished driving record, a hip taxi driver must chauffeur a loser police inspector on the trail of German bank robbers.",
                            DirectorId = 5,
                            GenreId = 5,
                            Image = "Taxi--730f60f3-73b5-4411-a970-ed5589c3af85.jpg",
                            Length = new TimeSpan(0, 1, 26, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7277),
                            Name = "Taxi",
                            Rating = 10.5,
                            Year = 1998
                        },
                        new
                        {
                            Id = 10,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7278),
                            Description = "The Manzoni family, a notorious mafia clan, is relocated to Normandy, France under the Witness Protection Program, where fitting in soon becomes challenging, as their old habits die hard.",
                            DirectorId = 5,
                            GenreId = 5,
                            Image = "The Family--b7bd1a39-9063-4a47-b7a2-117da0e272da.jpg",
                            Length = new TimeSpan(0, 1, 51, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7279),
                            Name = "The Family",
                            Rating = 9.6999999999999993,
                            Year = 2013
                        },
                        new
                        {
                            Id = 11,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the...",
                            DirectorId = 5,
                            GenreId = 2,
                            Image = "Leon The Professional--7619839c-e7ad-4e0a-af43-5e862b840725.jpg",
                            Length = new TimeSpan(0, 1, 50, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7280),
                            Name = "Léon: The Professional",
                            Rating = 10.9,
                            Year = 1994
                        },
                        new
                        {
                            Id = 12,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7282),
                            Description = "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
                            DirectorId = 2,
                            GenreId = 4,
                            Image = "The Prestige--b52f0f04-d67a-442e-8853-60667d5ff871.jpg",
                            Length = new TimeSpan(0, 2, 10, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7282),
                            Name = "The Prestige",
                            Rating = 10.199999999999999,
                            Year = 2006
                        },
                        new
                        {
                            Id = 13,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7284),
                            Description = "In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.",
                            DirectorId = 6,
                            GenreId = 1,
                            Image = "Shutter Island--90fea998-b36e-41cf-be61-d62a95eec933.jpg",
                            Length = new TimeSpan(0, 2, 18, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7284),
                            Name = "Shutter Island",
                            Rating = 10.4,
                            Year = 2010
                        },
                        new
                        {
                            Id = 14,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7285),
                            Description = "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster, which disguises itself as a clown and preys on the children of Derry, their small Maine town...",
                            DirectorId = 7,
                            GenreId = 1,
                            Image = "It--11df08d0-fb79-4999-8167-9fd1e5913fb8.jpg",
                            Length = new TimeSpan(0, 2, 15, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7286),
                            Name = "It",
                            Rating = 10.0,
                            Year = 2017
                        },
                        new
                        {
                            Id = 15,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7287),
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            DirectorId = 4,
                            GenreId = 2,
                            Image = "Pulp Fiction--204ed3ec-457b-4726-bbd1-5b81acade5be.jpg",
                            Length = new TimeSpan(0, 2, 34, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7288),
                            Name = "Pulp Fiction",
                            Rating = 11.800000000000001,
                            Year = 1994
                        },
                        new
                        {
                            Id = 16,
                            CreationTime = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7289),
                            Description = "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
                            DirectorId = 8,
                            GenreId = 3,
                            Image = "The Matrix--7a3d7838-91e7-4c5c-8e4a-277721761a50.jpg",
                            Length = new TimeSpan(0, 2, 16, 0, 0),
                            ModifiedDate = new DateTime(2021, 11, 22, 15, 15, 27, 27, DateTimeKind.Utc).AddTicks(7289),
                            Name = "The Matrix",
                            Rating = 11.300000000000001,
                            Year = 1999
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Domain.Entities.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Domain.Entities.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
